In [22]:
import pandas as pd
import numpy as np
# from datetime import datetime, date
import glob
import csv
import math

In [2]:
in_time = pd.read_csv("hr-analytics-case-study/in_time.csv")
out_time = pd.read_csv("hr-analytics-case-study/out_time.csv")

In [3]:
in_time.rename(columns = {"Unnamed: 0": "EmployeeID"}, inplace = True) 
out_time.rename(columns = {"Unnamed: 0": "EmployeeID"}, inplace = True)

In [4]:
in_time.head()
out_time.head()

,EmployeeID,2015-01-01,2015-01-02,2015-01-05,2015-01-06,2015-01-07,2015-01-08,2015-01-09,2015-01-12,2015-01-13,...,2015-12-18,2015-12-21,2015-12-22,2015-12-23,2015-12-24,2015-12-25,2015-12-28,2015-12-29,2015-12-30,2015-12-31
0,1,NaN,2015-01-02 16:56:15,2015-01-05 17:20:11,2015-01-06 17:19:05,2015-01-07 16:34:55,2015-01-08 17:08:32,2015-01-09 17:38:29,2015-01-12 16:58:39,2015-01-13 18:02:58,...,NaN,2015-12-21 17:15:50,2015-12-22 17:27:51,2015-12-23 16:44:44,2015-12-24 17:47:22,NaN,2015-12-28 18:00:07,2015-12-29 17:22:30,2015-12-30 17:40:56,2015-12-31 17:17:33
1,2,NaN,2015-01-02 18:22:17,2015-01-05 17:48:22,NaN,2015-01-07 17:09:06,2015-01-08 17:34:04,2015-01-09 16:52:29,2015-01-12 17:36:48,2015-01-13 18:00:13,...,2015-12-18 18:31:28,2015-12-21 17:34:16,2015-12-22 18:16:35,2015-12-23 17:38:18,NaN,NaN,2015-12-28 17:08:38,2015-12-29 17:54:46,2015-12-30 18:31:35,2015-12-31 17:40:58
2,3,NaN,2015-01-02 16:59:14,2015-01-05 17:06:46,2015-01-06 16:38:32,2015-01-07 16:33:21,2015-01-08 17:24:22,2015-01-09 16:57:30,2015-01-12 17:28:54,2015-01-13 17:21:25,...,2015-12-18 17:02:23,2015-12-21 17:20:17,2015-12-22 16:32:50,2015-12-23 16:59:43,2015-12-24 16:58:25,NaN,2015-12-28 16:43:31,2015-12-29 17:09:56,2015-12-30 17:06:25,2015-12-31 17:15:50
3,4,NaN,2015-01-02 17:25:24,2015-01-05 17:14:03,2015-01-06 17:07:42,2015-01-07 16:32:40,2015-01-08 16:53:11,2015-01-09 17:19:47,2015-01-12 17:13:37,2015-01-13 17:11:45,...,2015-12-18 17:55:23,2015-12-21 16:49:09,2015-12-22 17:24:00,2015-12-23 17:36:35,2015-12-24 16:48:21,NaN,2015-12-28 17:19:34,2015-12-29 16:58:16,2015-12-30 17:40:11,2015-12-31 17:09:14
4,5,NaN,2015-01-02 18:31:37,2015-01-05 17:49:15,2015-01-06 17:26:25,2015-01-07 17:37:59,2015-01-08 17:59:28,2015-01-09 17:44:08,2015-01-12 18:51:21,2015-01-13 18:14:58,...,2015-12-18 17:52:48,2015-12-21 17:43:35,2015-12-22 18:07:57,2015-12-23 18:00:49,2015-12-24 17:59:22,NaN,2015-12-28 17:44:59,2015-12-29 18:47:00,2015-12-30 17:15:33,2015-12-31 17:42:14

In [5]:
type(in_time['2015-01-02'])
in_time.iloc[:,1]

0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
        ..
4405   NaN
4406   NaN
4407   NaN
4408   NaN
4409   NaN
Name: 2015-01-01, Length: 4410, dtype: float64

In [6]:
for i in range(1,262):
    in_time.iloc[:,i] =  pd.to_datetime(in_time.iloc[:,i]).dt.time
    out_time.iloc[:,i] = pd.to_datetime(out_time.iloc[:,i]).dt.time

In [7]:
in_time['2015-01-02']
in_time.head()

,EmployeeID,2015-01-01,2015-01-02,2015-01-05,2015-01-06,2015-01-07,2015-01-08,2015-01-09,2015-01-12,2015-01-13,...,2015-12-18,2015-12-21,2015-12-22,2015-12-23,2015-12-24,2015-12-25,2015-12-28,2015-12-29,2015-12-30,2015-12-31
0,1,NaT,09:43:45,10:08:48,09:54:26,09:34:31,09:51:09,10:09:25,09:42:53,10:13:06,...,NaT,09:55:29,10:04:06,10:14:27,10:11:35,NaT,10:13:41,10:03:36,09:54:12,10:12:44
1,2,NaT,10:15:44,10:21:05,NaT,09:45:17,10:09:04,09:43:26,10:00:07,10:43:29,...,10:37:17,09:49:02,10:33:51,10:12:10,NaT,NaT,09:31:45,09:55:49,10:32:25,09:27:20
2,3,NaT,10:17:41,09:50:50,10:14:13,09:47:27,10:03:40,10:05:49,10:03:47,10:21:26,...,10:15:14,10:10:28,09:44:44,10:15:54,10:07:26,NaT,09:42:05,09:43:36,09:34:05,10:28:39
3,4,NaT,10:05:06,09:56:32,10:11:07,09:37:30,10:02:08,10:08:12,10:13:42,09:53:22,...,10:17:38,09:58:21,10:04:25,10:11:46,09:43:15,NaT,09:52:44,09:33:16,10:18:12,10:01:15
4,5,NaT,10:28:17,09:49:58,09:45:28,09:49:37,10:19:44,10:00:50,10:29:27,09:59:32,...,09:58:35,10:03:41,10:10:30,10:13:36,09:44:24,NaT,10:05:15,10:30:53,09:18:21,09:41:09

In [8]:
out_time.head()

,EmployeeID,2015-01-01,2015-01-02,2015-01-05,2015-01-06,2015-01-07,2015-01-08,2015-01-09,2015-01-12,2015-01-13,...,2015-12-18,2015-12-21,2015-12-22,2015-12-23,2015-12-24,2015-12-25,2015-12-28,2015-12-29,2015-12-30,2015-12-31
0,1,NaT,16:56:15,17:20:11,17:19:05,16:34:55,17:08:32,17:38:29,16:58:39,18:02:58,...,NaT,17:15:50,17:27:51,16:44:44,17:47:22,NaT,18:00:07,17:22:30,17:40:56,17:17:33
1,2,NaT,18:22:17,17:48:22,NaT,17:09:06,17:34:04,16:52:29,17:36:48,18:00:13,...,18:31:28,17:34:16,18:16:35,17:38:18,NaT,NaT,17:08:38,17:54:46,18:31:35,17:40:58
2,3,NaT,16:59:14,17:06:46,16:38:32,16:33:21,17:24:22,16:57:30,17:28:54,17:21:25,...,17:02:23,17:20:17,16:32:50,16:59:43,16:58:25,NaT,16:43:31,17:09:56,17:06:25,17:15:50
3,4,NaT,17:25:24,17:14:03,17:07:42,16:32:40,16:53:11,17:19:47,17:13:37,17:11:45,...,17:55:23,16:49:09,17:24:00,17:36:35,16:48:21,NaT,17:19:34,16:58:16,17:40:11,17:09:14
4,5,NaT,18:31:37,17:49:15,17:26:25,17:37:59,17:59:28,17:44:08,18:51:21,18:14:58,...,17:52:48,17:43:35,18:07:57,18:00:49,17:59:22,NaT,17:44:59,18:47:00,17:15:33,17:42:14

In [9]:
in_time = in_time.dropna(axis=1, how="all")
out_time = out_time.dropna(axis=1, how="all")

In [10]:
in_time

,EmployeeID,2015-01-02,2015-01-05,2015-01-06,2015-01-07,2015-01-08,2015-01-09,2015-01-12,2015-01-13,2015-01-15,...,2015-12-17,2015-12-18,2015-12-21,2015-12-22,2015-12-23,2015-12-24,2015-12-28,2015-12-29,2015-12-30,2015-12-31
0,1,09:43:45,10:08:48,09:54:26,09:34:31,09:51:09,10:09:25,09:42:53,10:13:06,10:01:24,...,NaT,NaT,09:55:29,10:04:06,10:14:27,10:11:35,10:13:41,10:03:36,09:54:12,10:12:44
1,2,10:15:44,10:21:05,NaT,09:45:17,10:09:04,09:43:26,10:00:07,10:43:29,09:37:57,...,09:15:08,10:37:17,09:49:02,10:33:51,10:12:10,NaT,09:31:45,09:55:49,10:32:25,09:27:20
2,3,10:17:41,09:50:50,10:14:13,09:47:27,10:03:40,10:05:49,10:03:47,10:21:26,09:55:11,...,09:53:17,10:15:14,10:10:28,09:44:44,10:15:54,10:07:26,09:42:05,09:43:36,09:34:05,10:28:39
3,4,10:05:06,09:56:32,10:11:07,09:37:30,10:02:08,10:08:12,10:13:42,09:53:22,10:00:50,...,09:54:36,10:17:38,09:58:21,10:04:25,10:11:46,09:43:15,09:52:44,09:33:16,10:18:12,10:01:15
4,5,10:28:17,09:49:58,09:45:28,09:49:37,10:19:44,10:00:50,10:29:27,09:59:32,10:06:12,...,09:46:35,09:58:35,10:03:41,10:10:30,10:13:36,09:44:24,10:05:15,10:30:53,09:18:21,09:41:09
5,6,09:43:08,10:14:00,10:08:42,10:18:15,10:33:09,10:19:13,09:48:30,09:54:26,10:33:28,...,09:34:35,10:24:55,09:44:43,09:38:00,09:53:27,09:38:46,NaT,09:51:47,10:20:39,09:55:25
6,7,10:20:13,09:30:01,09:48:47,09:46:18,09:59:29,10:13:26,09:23:42,10:00:14,09:57:31,...,09:12:24,10:12:15,09:52:10,NaT,10:22:03,10:24:29,10:19:47,09:44:16,10:05:48,10:04:10
7,8,09:57:10,09:48:56,09:54:04,09:52:31,09:58:31,09:53:12,09:58:57,09:42:05,10:23:51,...,09:46:03,10:16:27,10:12:52,10:58:57,09:45:12,09:46:29,09:59:24,09:54:34,09:43:37,10:33:00
8,9,NaT,10:01:42,09:50:56,10:02:57,10:07:22,09:59:54,10:14:55,NaT,09:52:53,...,10:00:12,10:19:42,10:18:09,09:39:54,09:48:05,10:00:32,NaT,10:06:27,10:17:59,09:28:41
9,10,09:55:53,10:21:06,10:03:01,10:06:01,09:52:25,09:36:12,09:59:26,10:08:33,NaT,...,10:17:05,09:57:20,09:39:07,10:17:05,10:25:33,10:21:01,10:20:31,10:12:14,10:08:04,10:00:21
10,11,09:57:48,10:00:35,10:40:08,09:48:52,09:22:55,10:12:43,10:17:22,10:22:04,09:43:44,...,10:13:58,09:40:38,10:18:03,09:49:53,10:15:05,09:47:30,09:44:04,10:06:46,10:02:09,09:50:19
11,12,09:37:33,10:27:04,09:47:47,09:32:46,09:54:18,10:34:58,10:16:06,10:12:42,10:04:37,...,10:14:39,09:51:58,10:11:41,09:52:37,10:04:33,10:07:13,10:23:34,09:41:17,NaT,10:03:20
12,13,NaT,09:58:51,09:57:02,NaT,10:02:04,09:50:42,09:56:19,10:09:57,10:05:45,...,10:21:49,10:23:12,10:15:12,10:30:36,09:19:44,09:44:32,09:42:02,09:44:17,10:24:47,10:08:39
13,14,10:15:31,10:07:45,09:51:45,10:34:41,09:34:23,10:06:45,09:45:05,09:23:53,09:53:05,...,09:55:18,10:02:03,09:55:11,10:02:30,09:59:28,09:44:41,09:42:15,10:04:48,10:12:04,09:48:07
14,15,09:54:30,10:11:12,09:44:02,09:51:12,10:08:06,10:06:00,09:51:47,NaT,10:14:42,...,10:18:39,09:53:40,09:55:14,10:13:58,09:53:31,10:20:33,09:33:33,09:27:22,09:50:25,10:18:16
15,16,09:47:51,09:54:34,10:38:02,10:31:11,09:55:37,10:05:09,10:04:41,09:31:07,10:13:24,...,09:54:42,09:44:33,10:05:42,10:17:28,10:11:41,09:48:22,10:04:12,10:16:01,09:30:51,09:37:55
16,17,10:08:00,09:59:14,10:00:51,10:30:37,09:54:41,10:04:45,09:29:22,10:24:25,10:01:39,...,09:47:29,10:16:42,10:29:44,09:34:22,09:37:51,09:48:50,10:09:22,10:00:01,10:09:10,09:42:50
17,18,10:18:02,10:01:45,NaT,09:41:42,10:00:25,09:53:17,10:06:48,09:51:34,10:26:52,...,10:21:51,10:01:02,10:07:45,10:25:43,09:46:50,09:58:34,10:04:34,10:05:40,09:39:06,09:34:19
18,19,10:27:00,10:23:10,10:05:45,10:18:26,10:18:51,09:35:35,10:03:42,10:16:42,09:30:44,...,09:46:58,09:52:50,09:41:36,09:47:02,NaT,09:44:50,10:12:05,09:45:06,09:46:10,09:33:20
19,20,09:49:37,10:23:07,10:41:38,10:11:02,10:02:22,10:04:51,10:13:04,09:59:13,10:15:12,...,10:27:13,10:23:19,09:43:33,10:04:58,NaT,09:34:25,10:36:25,09:45:01,10:25:31,10:05:10
20,21,10:01:07,09:47:36,10:14:40,09:49:46,09:55:05,09:38:24,10:06:11,10:11:28,10:45:55,...,09:49:56,09:57:37,NaT,10:09:32,10:17:37,10:07:43,10:03:42,10:23:11,09:51:09,10:19:03
21,22,09:35:02,09:36:53,10:10:40,10:03:36,09:43:50,10:03:43,10:11:00,09:50:39,09:43:40,...,09:46:17,09:35:40,09:52:31,09:45:16,09:42:16,NaT,NaT,10:04:19,10:12:49,NaT
22,23,10:03:47,09:48:30,NaT,10:03:25,NaT,09:55:30,09:59:14,10:13:50,NaT,...,10:02:45,10:11:33,09:56:31,09:56:31,10:10:40,10:15:30,10:19:02,09:50:01,09:49:28,09:42:34
23,24,09:42:07,10:08:12,10:03:02,10:28:11,09:48:54,NaT,09:53:09,09:47:30,10:24:00,...,09:49:17,09:30:13,10:20:17,10:08:39,09:55:59,10:08:23,09:51:12,10:13:04,10:19:33,10:24:08
24,25,09:54:16,10:41:15,10:02:09,09:53:16,09:32:45,09:26:15,09:45:13,09:42:47,09:25:18,...,10:07:41,NaT,09:59:33,10:03:04,09:48:23,10:19:00,10:16:09,NaT,09:57:18,10:07:28
25,26,10:31:53,09:48:29,10:13:17,10:24:05,10:02:38,10:17:40,10:08:06,10:02:06,10:00:05,...,09:47:44,09:44:30,09:53:11,10:07:28,09:52:06,10:07:51,10:30:26,09:50:51,10:04:31,10:06:48
26,27,10:22:11,10:06:05,10:12:51,10:04:04,10:14:59,10:04:37,10:14:01,10:18:51,09:58:03,...,09:54:20,09:44:31,09:45:09,09:31:30,10:01:45,10:08:21,10:11:03,10:08:21,10:05:35,10:09:10
27,28,09:35:51,10:07:10,09:57:56,10:15:23,10:00:02,10:09:17,10:13:24,NaT,09:55:26,...,10:03:47,10:39:38,09:51:38,09:39:56,10:18:34,10:03:11,09:49:38,10:20:49,10:02:05,09:53:49
28,29,10:14:29,09:39:12,09:40:42,10:18:22,10:10:49,10:30:43,09:56:28,10:18:10,10:34:55,...,10:03:36,10:05:19,10:12:31,10:05:26,09:57:58,10:12:56,09:58:06,10:11:18,10:15:37,09:58:59
29,30,NaT,10:19:49,09:33:28,10:03:50,10:23:34,10:06:07,10:12:11,10:08:58,NaT,...,09:45:22,10:29:20,10:11:56,10:14:10,10:11:34,09:59:40,09:36:18,09:21:49,09:49:28,09:32:18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4380,4381,10:10:44,09:43:15,09:30:37,09:50:52,10:05:24,10:13:12,NaT,09:54:31,10:11:17,...,10:40:48,09:41:05,09:49:38,09:59:41,09:48:49,10:14:10,09:55:28,09:28:19,10:10:42,10:09:20
4381,4382,09:50:44,10:03:38,10:07:53,10:05:35,09:38:35,09:54:56,09:26:16,10:09:06,09:42:04,...,09:50:11,10:28:14,10:03:06,09:37:32,10:26:07,10:34:08,10:04:32,09:54:08,10:02:35,09:55:22
4382,4383,09:53:07,09:52:22,09:27:43,09:44:21,10:07:42,09:58:18,09:30:00,NaT,09:50:54,...,10:08:08,09:12:24,09:55:38,09:36:45,09:55:11,10:18:26,10:31:24,10:08:41,10:21:44,09:45:58
4383,4384,09:52:24,09:38:57,09:46:46,09:39:34,10:03:50,10:04:02,09:54:55,10:00:47,10:02:19,...,09:58:30,09:58:25,09:51:25,10:09:32,10:24:37,09:31:59,09:49:27,09:37:20,09:59:19,09:46:19
4384,4385,09:50:41,10:08:03,09:46:27,09:29:42,09:55:03,09:52:00,09:36:03,10:06:05,10:00:16,...,09:54:23,10:25:48,10:21:21,NaT,09:56:08,09:49:15,09:43:44,10:15:59,NaT,09:58:51
4385,4386,10:08:11,10:20:05,09:52:39,10:09:28,10:23:45,10:19:46,10:00:39,09:55:24,NaT,...,10:16:34,09:48:28,10:01:04,10:28:06,10:11:10,10:21:57,10:10:20,NaT,09:58:51,09:55:48
4386,4387,NaT,10:06:05,09:35:35,10:29:52,09:54:58,10:22:43,10:26:55,09:42:51,10:17:24,...,09:48:34,09:51:51,10:06:29,09:42:57,10:25:18,10:07:21,09:40:49,09:48:15,NaT,10:04:24
4387,4388,10:10:11,09:48:11,10:06:07,10:00:06,NaT,10:09:20,10:13:53,10:04:42,09:38:21,...,09:48:21,10:03:54,09:59:16,10:09:14,09:50:54,09:48:29,10:03:59,09:52:43,10:19:18,10:10:06
4388,4389,10:14:32,10:16:22,10:07:32,10:20:17,09:42:19,09:36:19,09:47:27,09:49:50,09:56:24,...,09:58:54,09:37:04,09:43:30,10:08:50,NaT,10:02:43,10:07:31,10:12:29,09:58:30,09:36:27
4389,4390,09:54:44,10:15:08,10:12:09,10:07:23,10:07:38,10:04:49,09:40:40,10:06:53,10:08:37,...,09:37:21,10:01:59,09:40:34,10:10:50,09:55:22,10:14:43,09:49:37,09:08:24,10:32:41,10:16:30
4390,4391,10:06:00,09:40:28,09:58:16,10:00:58,09:57:07,09:54:34,10:10:47,10:11:48,09:15:42,...,09:55:08,10:22:47,09:58:04,10:44:09,10:17:05,09:43:13,09:53:08,10:02:51,09:43:44,09:49:40
4391,4392,09:59:20,10:15:19,10:30:22,09:48:40,10:05:18,10:28:24,09:48:53,10:02:07,10:45:33,...,10:14:27,09:43:32,10:03:05,09:51:35,10:35:14,10:14:07,NaT,NaT,09:51:08,09:53:57
4392,4393,10:22:23,09:33:35,10:14:17,09:46:19,10:17:29,10:16:16,10:10:06,09:53:59,NaT,...,09:20:03,09:56:14,09:52:02,09:43:12,09:57:04,10:21:11,09:38:38,10:10:24,10:12:27,09:38:01
4393,4394,10:07:29,10:20:12,10:18:32,09:56:36,10:12:50,09:31:02,10:16:47,09:55:12,09:49:04,...,10:13:03,NaT,10:21:06,09:49:55,09:46:31,10:01:29,10:08:23,09:35:09,10:11:08,09:53:16
4394,4395,10:33:43,09:55:05,09:54:28,09:50:46,09:29:35,10:05:39,10:01:24,NaT,10:04:55,...,10:13:31,09:57:12,10:01:57,10:06:22,09:31:10,09:57:48,10:00:07,10:02:39,10:05:55,09:58:11
4395,4396,10:23:05,09:55:36,09:56:43,10:07:38,09:59:47,10:06:52,09:38:11,09:57:34,10:11:25,...,09:51:52,09:51:08,10:23:25,09:49:13,10:41:17,09:55:59,09:40:32,10:04:49,10:10:23,09:56:08
4396,4397,10:01:45,10:07:16,10:08:14,10:04:01,10:20:41,09:52:15,09:45:29,10:21:57,09:55:47,...,09:55:27,09:48:23,09:44:17,09:55:29,10:20:04,NaT,10:20:47,10:11:42,09:57:06,09:40:31
4397,4398,09:47:07,10:29:05,09:42:05,10:05:46,10:14:04,10:08:47,09:54:52,09:51:02,09:51:04,...,10:10:26,09:44:03,10:06:17,09:58:19,10:05:15,09:51:32,09:50:22,09:29:46,10:33:12,10:04:14
4398,4399,10:09:20,09:53:55,10:15:46,10:21:11,09:50:38,09:58:38,09:49:02,09:47:40,10:09:35,...,10:03:32,10:11:14,10:32:58,10:13:47,10:26:11,10:14:58,10:08:59,10:34:59,09:56:31,09:32:47
4399,4400,10:10:01,10:18:25,10:05:46,09:52:12,10:13:48,NaT,10:07:06,10:07:15,09:56:26,...,09:51:56,09:50:34,10:26:00,NaT,09:43:05,09:52:32,10:05:55,10:18:23,NaT,09:52:29
4400,4401,09:42:53,09:29:53,09:35:10,09:27:31,09:36:54,10:08:16,09:58:21,10:03:53,10:23:33,...,09:38:15,09:46:52,10:02:06,10:17:44,10:19:08,09:41:55,09:50:17,10:09:06,10:10:06,10:21:47
4401,4402,10:19:31,10:02:53,09:38:17,09:52:22,09:58:34,09:25:13,10:16:16,10:22:13,10:05:18,...,09:47:13,09:55:26,10:11:49,10:09:52,10:07:32,10:06:01,10:15:17,10:03:38,10:02:35,09:36:28
4402,4403,10:00:39,09:48:34,09:42:54,10:04:11,09:40:07,10:32:53,NaT,09:42:32,10:05:31,...,09:37:06,10:28:26,09:45:16,09:59:02,10:25:14,09:41:59,10:11:33,09:54:20,09:48:16,09:44:36
4403,4404,10:03:28,10:12:53,09:45:49,09:52:01,10:00:21,09:58:14,10:08:21,NaT,09:58:35,...,10:04:27,10:01:17,10:25:09,09:58:36,09:51:22,09:49:51,10:18:13,09:44:52,09:56:32,10:11:35
4404,4405,10:18:28,09:42:42,10:08:36,09:43:44,10:01:57,10:09:09,09:52:17,09:47:41,10:15:27,...,09:40:07,09:48:29,10:12:51,10:15:09,10:05:50,10:30:00,10:07:07,09:57:23,09:23:37,09:50:05
4405,4406,09:20:32,10:17:53,10:26:51,10:06:58,09:45:06,09:49:24,09:37:10,09:25:02,09:29:17,...,10:05:22,10:01:06,10:25:25,10:16:11,10:04:40,09:45:40,10:15:39,10:10:09,09:28:19,10:00:12
4406,4407,10:03:41,NaT,09:44:00,09:42:10,10:00:57,09:44:04,10:07:32,10:05:11,10:18:11,...,09:45:49,09:27:32,09:41:24,09:50:30,10:32:21,09:47:41,09:54:23,10:13:32,10:21:09,10:09:48
4407,4408,10:01:01,09:33:00,09:49:17,10:28:12,09:47:38,10:01:03,09:49:12,09:47:10,10:08:31,...,10:01:36,10:00:57,09:51:07,10:02:10,09:58:29,09:56:05,09:59:24,NaT,10:02:36,10:03:30
4408,4409,10:17:05,10:02:27,10:12:50,10:12:31,09:42:57,NaT,10:00:38,09:48:03,09:04:17,...,09:51:40,09:54:33,10:01:08,10:10:19,09:42:30,09:56:05,09:55:25,09:54:42,10:15:44,09:56:47
4409,4410,09:59:09,10:16:14,09:52:30,09:43:15,10:06:55,10:27:39,09:47:35,09:30:00,10:08:19,...,09:58:17,10:20:40,10:26:02,NaT,09:53:19,09:42:13,09:41:11,10:05:15,10:32:49,10:09:28

In [11]:
# in_time.isna().sum() #250
out_time.isna().sum() #250

EmployeeID      0
2015-01-02    209
2015-01-05    206
2015-01-06    228
2015-01-07    209
             ...
2015-12-24    250
2015-12-28    234
2015-12-29    230
2015-12-30    265
2015-12-31    213
Length: 250, dtype: int64

In [12]:
joined_timings = pd.merge(in_time, out_time, on='EmployeeID')

In [13]:
# joined_timings.iloc[:,1:250] #2015-01-02 ->2015-12-31
# joined_timings.iloc[:,250:499]
emp_in = in_time.iloc[:,1:]
emp_in = np.array(emp_in)
emp_out = out_time.iloc[:,1:]
emp_out = np.array(emp_out)

In [14]:
emp_out.shape

(4410, 249)

In [15]:
# for i in range(1,250):
#     for j in range(0, 4410):
#         emp_in = joined_timings.iloc[j,i]
#         emp_out = joined_timings.iloc[j,i+249]
# #         print(type(emp_in))
# #         diff = emp_out - emp_in
# #         print(emp_out.hour)
# #         print(emp_out.minute)
#         diff_h = (emp_out.hour - emp_in.hour)*60*60
#         diff_m = (emp_out.minute - emp_in.minute)*60
#         diff_s = emp_out.second - emp_in.second
# #         print(diff_h)
#         joined_timings.iloc[j,i] = (diff_h+diff_m+diff_s)
#     joined_timings.drop(joined_timings.columns[i+249], axis=1, inplace=True)
# eid = joined_timings.iloc[:,0:1]
# x = joined_timings.iloc[:,250:499]
# y = joined_timings.iloc[:,1:250]
# in_y = np.array(y)
# out_x = np.array(x)

# sub_time = []
# sub_time.append(in_time.columns)
# # in_y = pd.DataFrame(y)
# out_x = pd.DataFrame(x)
# sub_time = joined_timings.iloc[:,251:499] - joined_timings.iloc[:,1:250]
# sub_time = out_x.subtract(in_y)

sub_time = []
# sub_time.append(in_time.columns)

# sub_time = np.array(sub_time)
for i in range(4410):
    t = []
    t.append(i+1)
    for j in range(249):
        diff_h = (emp_out[i][j].hour - emp_in[i][j].hour)*60*60
        diff_m = (emp_out[i][j].minute - emp_in[i][j].minute)
        diff_s = emp_out[i][j].second - emp_in[i][j].second
        time_worked = diff_h + diff_m + diff_s
        t.append(time_worked)
    sub_time.append(t)

In [16]:
# out_x[0][1].second
in_time.columns

Index(['EmployeeID', '2015-01-02', '2015-01-05', '2015-01-06', '2015-01-07',
       '2015-01-08', '2015-01-09', '2015-01-12', '2015-01-13', '2015-01-15',
       ...
       '2015-12-17', '2015-12-18', '2015-12-21', '2015-12-22', '2015-12-23',
       '2015-12-24', '2015-12-28', '2015-12-29', '2015-12-30', '2015-12-31'],
      dtype='object', length=250)

In [19]:
with open('foo.csv', 'w') as output_file:
    writer = csv.writer(output_file)
    writer.writerows([in_time.columns])
    for row in range(4410):
        writer.writerows([sub_time[row]])

In [42]:

time_worked_year_leave = []
for i in range(4410):
    count = 0
    sum_seconds = 0
    for j in range(249):
        if math.isnan(sub_time[i][j]):
            count = count + 1
        else:
            sum_seconds = sum_seconds + sub_time[i][j]
    time_worked_year_leave.append([i+1, ((sum_seconds/3600)/(249-count)), count])
#     time_worked_year.append([i+1, sum_seconds])

In [43]:
time_worked_year_leave

[[1, 7.343133381226054, 17],
 [2, 7.684110169491525, 13],
 [3, 6.985200872359964, 7],
 [4, 7.1633297872340425, 14],
 [5, 7.973453514739229, 4],
 [6, 10.750371542428503, 12],
 [7, 6.893963122605364, 17],
 [8, 6.698261316872428, 6],
 [9, 7.205786231884058, 19],
 [10, 7.049985754985755, 15],
 [11, 8.367366297833103, 8],
 [12, 7.03846357768557, 8],
 [13, 9.259194565744783, 20],
 [14, 9.360973995271866, 14],
 [15, 6.06468418626095, 8],
 [16, 6.676357243319268, 12],
 [17, 6.5935364659813995, 22],
 [18, 10.968026196928635, 3],
 [19, 6.930534003831418, 17],
 [20, 9.253897306397306, 18],
 [21, 7.55735632183908, 17],
 [22, 5.982961775878443, 15],
 [23, 8.366132662835248, 17],
 [24, 6.777773186409551, 7],
 [25, 7.060995670995671, 18],
 [26, 9.322344398340249, 8],
 [27, 10.931961878196189, 10],
 [28, 7.572020951035781, 13],
 [29, 10.931820987654321, 6],
 [30, 6.803705314009662, 19],
 [31, 10.066789215686276, 11],
 [32, 6.6819421487603305, 7],
 [33, 10.473887701804369, 15],
 [34, 6.156178555098308, 6],
 [35, 6.559850694444445, 9],
 [36, 10.230911159003831, 17],
 [37, 9.94083792470156, 7],
 [38, 5.953727753727754, 18],
 [39, 6.746113558492413, 22],
 [40, 7.659632728963273, 10],
 [41, 7.174048269581057, 5],
 [42, 7.5628203309692665, 14],
 [43, 6.9246854912764, 7],
 [44, 6.980431712962964, 9],
 [45, 7.173760245901639, 5],
 [46, 7.1430995370370365, 9],
 [47, 7.603353427895981, 14],
 [48, 7.801306844819503, 12],
 [49, 6.944011257953989, 22],
 [50, 6.875713937621833, 21],
 [51, 10.850880394857668, 7],
 [52, 9.085181669010781, 12],
 [53, 6.802483728498373, 10],
 [54, 7.286554849340867, 13],
 [55, 8.573911657559199, 5],
 [56, 6.75640289449113, 11],
 [57, 10.939833333333334, 4],
 [58, 7.652794909446891, 22],
 [59, 9.910061728395062, 6],
 [60, 7.8728998140399815, 10],
 [61, 10.628275273224045, 5],
 [62, 10.450948396094839, 10],
 [63, 10.024330206830205, 18],
 [64, 6.5799199817101055, 6],
 [65, 7.466729957805907, 12],
 [66, 10.683593117408906, 2],
 [67, 6.158077107279694, 17],
 [68, 6.5817927068037205, 22],
 [69, 6.049016812865497, 21],
 [70, 9.933954381210478, 3],
 [71, 7.390103305785124, 7],
 [72, 6.468143575674439, 6],
 [73, 6.272205673758865, 14],
 [74, 9.276111111111112, 18],
 [75, 6.071781115879828, 16],
 [76, 7.187316760037348, 11],
 [77, 7.068233471074381, 7],
 [78, 9.869316979316979, 18],
 [79, 10.430812801932367, 19],
 [80, 6.877052533705253, 10],
 [81, 7.556499042145594, 17],
 [82, 6.0535963114754106, 5],
 [83, 5.976346516007532, 13],
 [84, 8.942592975206612, 7],
 [85, 10.38109360410831, 11],
 [86, 8.353748861566483, 5],
 [87, 7.87826895565093, 16],
 [88, 7.074786685419597, 12],
 [89, 9.646907252440725, 10],
 [90, 7.73778010227801, 10],
 [91, 6.2598077824660106, 12],
 [92, 6.279723414401526, 16],
 [93, 8.794450536062378, 21],
 [94, 7.689203783524904, 17],
 [95, 7.286533142584644, 16],
 [96, 10.754699730094467, 2],
 [97, 10.360205215419501, 4],
 [98, 5.967674897119341, 6],
 [99, 6.0889307298930735, 10],
 [100, 8.101525500910746, 5],
 [101, 7.2744468390804595, 17],
 [102, 7.074512138188609, 11],
 [103, 6.300663120567376, 14],
 [104, 8.091306628516929, 16],
 [105, 7.951073508005822, 20],
 [106, 10.463911736411736, 18],
 [107, 7.959921837421837, 18],
 [108, 6.079044834307992, 21],
 [109, 7.555096566523606, 16],
 [110, 6.856496376811594, 19],
 [111, 9.256169278252612, 15],
 [112, 10.762721318879855, 3],
 [113, 5.968657004830918, 19],
 [114, 7.753492063492064, 4],
 [115, 7.684691619585688, 13],
 [116, 6.163249408983452, 14],
 [117, 7.091266762452108, 17],
 [118, 7.792879629629629, 9],
 [119, 7.586415692007797, 21],
 [120, 5.9754107312440645, 15],
 [121, 9.074159574468084, 14],
 [122, 8.64555202448211, 13],
 [123, 9.946962560386474, 19],
 [124, 6.870834535834536, 18],
 [125, 6.972322916666667, 9],
 [126, 6.260660173160174, 18],
 [127, 6.34030131826742, 13],
 [128, 8.158469907407406, 9],
 [129, 6.424034722222222, 9],
 [130, 6.653783816425121, 19],
 [131, 7.451971631205674, 14],
 [132, 9.878820861678005, 4],
 [133, 7.384372645951036, 13],
 [134, 7.4655450513538755, 11],
 [135, 5.9741421928536464, 22],
 [136, 6.831850664767331, 15],
 [137, 6.106118295019157, 17],
 [138, 7.643087371512482, 22],
 [139, 8.842427637721755, 11],
 [140, 10.849971264367815, 17],
 [141, 10.646887219837863, 16],
 [142, 7.02826867816092, 17],
 [143, 8.973232426303854, 4],
 [144, 7.389343328684333, 10],
 [145, 7.555549886621315, 4],
 [146, 6.597149608114338, 8],
 [147, 6.165329566854991, 13],
 [148, 6.44641713747646, 13],
 [149, 8.159871970736168, 6],
 [150, 6.75860525082044, 12],
 [151, 7.26910401891253, 14],
 [152, 6.793288030519791, 16],
 [153, 7.288927536231884, 19],
 [154, 6.138374042145594, 17],
 [155, 7.577944210032817, 12],
 [156, 6.567558356676004, 11],
 [157, 10.603961864406779, 13],
 [158, 6.177432697014195, 22],
 [159, 8.556801453352087, 12],
 [160, 5.975566378066378, 18],
 [161, 6.254591287322565, 22],
 [162, 7.872197293447294, 15],
 [163, 7.145337465564738, 7],
 [164, 6.623552508204407, 12],
 [165, 7.873746438746439, 15],
 [166, 6.691753835425383, 10],
 [167, 6.262861952861953, 18],
 [168, 7.149756515775034, 6],
 [169, 6.259292824074074, 9],
 [170, 7.187877585377585, 18],
 [171, 7.775394927536232, 19],
 [172, 6.779373278236915, 7],
 [173, 6.455838081671415, 15],
 [174, 7.621556016597511, 8],
 [175, 7.5524085944919275, 15],
 [176, 9.138287037037037, 15],
 [177, 6.351532485875706, 13],
 [178, 8.442623456790123, 15],
 [179, 6.937608151183971, 5],
 [180, 6.449709543568465, 8],
 [181, 8.838877410468319, 7],
 [182, 6.557152777777778, 21],
 [183, 10.948449367088607, 12],
 [184, 7.777781308851225, 13],
 [185, 7.200660291438981, 5],
 [186, 6.392773029439696, 15],
 [187, 6.751800144300144, 18],
 [188, 7.359581560283688, 14],
 [189, 6.166211352657005, 19],
 [190, 5.991782308059132, 16],
 [191, 7.271281876138434, 5],
 [192, 7.034543158861341, 7],
 [193, 8.689505280073462, 7],
 [194, 10.760244821092279, 13],
 [195, 7.377152163225173, 23],
 [196, 9.15109858834244, 5],
 [197, 7.360795565302144, 21],
 [198, 7.370374596588289, 8],
 [199, 6.682805080721748, 15],
 [200, 9.19117796219456, 8],
 [201, 6.851897954439796, 10],
 [202, 9.253451690821256, 19],
 [203, 5.991048034934498, 20],
 [204, 6.299783138401559, 21],
 [205, 6.377934833567745, 12],
 [206, 8.714436099189317, 16],
 [207, 7.3591875, 9],
 [208, 6.167392787524366, 21],
 [209, 7.674916317991632, 10],
 [210, 7.473812816966344, 8],
 [211, 9.037226775956285, 5],
 [212, 5.970261641309359, 8],
 [213, 6.006360192837466, 7],
 [214, 5.993934216643422, 10],
 [215, 6.869372948898265, 12],
 [216, 10.735193637621025, 8],
 [217, 8.944450456950456, 18],
 [218, 7.353289894833105, 6],
 [219, 6.794828783524904, 17],
 [220, 6.762970173041895, 5],
 [221, 7.375780714635341, 22],
 [222, 10.781936540198735, 3],
 [223, 6.847749165474487, 16],
 [224, 8.871151996151998, 18],
 [225, 6.656767782426778, 10],
 [226, 7.889374709437471, 10],
 [227, 6.283716761633428, 15],
 [228, 7.854393305439331, 10],
 [229, 8.845736168267031, 6],
 [230, 7.060660009182736, 7],
 [231, 7.458777777777778, 14],
 [232, 8.649595238095237, 4],
 [233, 6.7761489898989895, 7],
 [234, 9.087319387288522, 6],
 [235, 6.988465775902485, 12],
 [236, 6.6745687134502925, 21],
 [237, 8.3670255126371, 16],
 [238, 6.454877963737797, 10],
 [239, 7.202826086956522, 19],
 [240, 8.653031609195402, 17],
 [241, 6.010558002936858, 22],
 [242, 7.251884160756501, 14],
 [243, 9.338022268135905, 7],
 [244, 7.280119549929676, 12],
 [245, 7.082956264775413, 14],
 [246, 7.408071827057183, 10],
 [247, 7.542130847953216, 21],
 [248, 9.920450819672132, 5],
 [249, 6.186278011204482, 11],
 [250, 6.780857075023742, 15],
 [251, 6.62758321612752, 12],
 [252, 7.484369834710744, 7],
 [253, 6.3825304580896685, 21],
 [254, 10.657905532114393, 12],
 [255, 6.974708937198067, 19],
 [256, 8.593282194328218, 10],
 [257, 10.360068879855465, 3],
 [258, 6.703549783549783, 18],
 [259, 7.062173551756885, 15],
 [260, 7.648778238819733, 8],
 [261, 6.771952479338843, 7],
 [262, 7.768905870936438, 20],
 [263, 7.0684214975845405, 19],
 [264, 8.847713675213674, 15],
 [265, 7.570767831149928, 20],
 [266, 9.081428410117436, 3],
 [267, 6.793002873563219, 17],
 [268, 7.479760258183495, 8],
 [269, 6.686590367191226, 16],
 [270, 7.862649572649572, 15],
 [271, 8.170660569105692, 3],
 [272, 7.133258226037196, 16],
 [273, 6.482135642135642, 18],
 [274, 7.898416666666666, 19],
 [275, 6.688751197318008, 17],
 [276, 8.581067493112947, 7],
 [277, 6.724556763285024, 19],
 [278, 7.678368820362213, 22],
 [279, 6.583241912798875, 12],
 [280, 7.315351617440225, 12],
 [281, 6.139520743919886, 16],
 [282, 7.352438815467449, 22],
 [283, 8.061659388646287, 20],
 [284, 5.993760504201681, 11],
 [285, 9.769654294032025, 20],
 [286, 6.082027431996312, 8],
 [287, 8.269638888888888, 19],
 [288, 7.488315450643777, 16],
 [289, 6.379127800640147, 6],
 [290, 9.964101851851852, 9],
 [291, 7.065018832391714, 13],
 [292, 6.381881572930956, 6],
 [293, 7.769740259740259, 18],
 [294, 6.270654679575842, 8],
 [295, 7.104422985216977, 16],
 [296, 8.762762345679013, 15],
 [297, 7.469896402550091, 5],
 [298, 7.052512130033964, 20],
 [299, 6.24854870288791, 22],
 [300, 7.06753367003367, 18],
 [301, 7.770411160058738, 22],
 [302, 10.85793366150961, 12],
 [303, 6.166115779645191, 11],
 [304, 5.969108946608947, 18],
 [305, 10.007871148459385, 11],
 [306, 7.646012931034483, 17],
 [307, 5.953099290780141, 14],
 [308, 7.9454645593869735, 17],
 [309, 9.967116858237548, 17],
 [310, 7.750477003642987, 5],
 [311, 7.943235704323571, 10],
 [312, 7.372654454022989, 17],
 [313, 7.183558310376492, 7],
 [314, 7.050513649425287, 17],
 [315, 6.267152777777778, 9],
 [316, 6.1691727053140095, 19],
 [317, 6.1759681543468155, 10],
 [318, 8.873132969034607, 5],
 [319, 6.780601073762838, 11],
 [320, 9.415780749885688, 6],
 [321, 10.765985996326904, 7],
 [322, 6.8963215488215495, 18],
 [323, 7.768188752276867, 5],
 [324, 7.136413255360624, 21],
 [325, 6.428928898033837, 6],
 [326, 7.903597768073751, 20],
 [327, 7.791657483930211, 7],
 [328, 7.941660806375996, 12],
 [329, 6.788725218994928, 8],
 [330, 6.04705227379278, 12],
 [331, 6.381979755178907, 13],
 [332, 10.65212141577061, 1],
 [333, 6.956698939603504, 8],
 [334, 7.952974058769513, 7],
 [335, 9.42874183006536, 11],
 [336, 7.6809088693957115, 21],
 [337, 7.692018359561278, 16],
 [338, 8.859626436781609, 17],
 [339, 7.749854664791373, 12],
 [340, 10.42614703065134, 17],
 [341, 6.175739130434783, 19],
 [342, 6.5910099902534105, 21],
 [343, 7.95895474137931, 17],
 [344, 6.8575886015325676, 17],
 [345, 9.337551020408162, 4],
 [346, 6.594349446849447, 18],
 [347, 7.550595564700503, 6],
 [348, 7.56404958677686, 7],
 [349, 6.843651300236407, 14],
 [350, 6.261071428571428, 18],
 [351, 6.348731725146198, 21],
 [352, 7.305399230399231, 18],
 [353, 10.450254036087369, 15],
 [354, 6.964233193277311, 11],
 [355, 9.867702641165756, 5],
 [356, 6.866524334251607, 7],
 [357, 7.9639094202898555, 19],
 [358, 7.282511337868481, 4],
 [359, 6.0884054834054835, 18],
 [360, 6.293134588563459, 10],
 [361, 6.39078081232493, 11],
 [362, 5.995095666205624, 8],
 [363, 6.873695286195287, 18],
 [364, 9.66165011820331, 14],
 [365, 7.756834045584045, 15],
 [366, 6.384099033816425, 19],
 [367, 10.34878231292517, 4],
 [368, 8.487776605719644, 12],
 [369, 6.560695592286502, 7],
 [370, 7.55457383665717, 15],
 [371, 6.078819732595666, 8],
 [372, 6.264209495839451, 22],
 [373, 6.455488505747127, 17],
 [374, 10.93869719926538, 7],
 [375, 7.974613997113996, 18],
 [376, 7.562001836547291, 7],
 [377, 10.368835162322815, 6],
 [378, 8.75905749636099, 20],
 [379, 9.958281625781625, 18],
 [380, 7.848947113051916, 20],
 [381, 7.760596577590248, 12],
 [382, 7.4387840018441675, 8],
 [383, 7.530952898550725, 19],
 [384, 6.786185579196217, 14],
 [385, 6.9591937382297555, 13],
 [386, 9.574632728963273, 10],
 [387, 10.055383101851852, 9],
 [388, 9.35790748393021, 7],
 [389, 6.340156175488794, 16],
 [390, 7.075427259887006, 13],
 [391, 7.376800236406619, 14],
 [392, 6.642720856102003, 5],
 [393, 7.555641025641026, 15],
 [394, 10.638186475409837, 5],
 [395, 8.272830520393812, 12],
 [396, 6.58323343079922, 21],
 [397, 6.855286848072562, 4],
 [398, 9.376923258003766, 13],
 [399, 9.985916554206028, 2],
 [400, 6.424813642756681, 12],
 [401, 9.732411668991167, 10],
 [402, 6.38858541360744, 22],
 [403, 10.459404599271402, 5],
 [404, 6.550365375749194, 8],
 [405, 7.075156695156695, 15],
 [406, 7.846861678004536, 4],
 [407, 10.257326958105645, 5],
 [408, 8.449343647444914, 12],
 [409, 9.760886353158137, 8],
 [410, 10.366194083694083, 18],
 [411, 7.644830508474577, 13],
 [412, 10.621729428172943, 10],
 [413, 7.64825430032543, 10],
 [414, 7.69183830171635, 3],
 [415, 6.848670808966861, 21],
 [416, 10.504573996265174, 11],
 [417, 8.287217573221758, 10],
 [418, 6.0574417009602195, 6],
 [419, 10.337051820728291, 11],
 [420, 6.962323557463042, 16],
 [421, 6.670605532310553, 10],
 [422, 7.055329007285974, 5],
 [423, 6.475012784751279, 10],
 [424, 7.054204234972678, 5],
 [425, 7.054561524334252, 7],
 [426, 8.863392942298521, 16],
 [427, 6.038818829891839, 23],
 [428, 7.612222222222223, 8],
 [429, 10.666516452074392, 16],
 [430, 7.065695611577965, 11],
 [431, 10.570610880590134, 8],
 [432, 6.05715909090909, 7],
 [433, 8.293826358826358, 18],
 [434, 8.109337868480726, 4],
 [435, 7.860237588652482, 14],
 [436, 9.76542194092827, 12],
 [437, 5.991152094717669, 5],
 [438, 6.247520802741067, 22],
 [439, 6.281029067041725, 12],
 [440, 7.586973556525958, 20],
 [441, 6.345185185185185, 12],
 [442, 6.961059757236227, 11],
 [443, 7.442393719806764, 19],
 [444, 6.495912534435261, 7],
 [445, 7.9693583212033, 20],
 [446, 8.065271712760795, 20],
 [447, 7.286571729957806, 12],
 [448, 6.48198309178744, 19],
 [449, 9.436612751992499, 12],
 [450, 10.049379432624113, 14],
 [451, 6.778399908172636, 7],
 [452, 8.153863211951448, 11],
 [453, 7.901125478927203, 17],
 [454, 10.238069620253166, 12],
 [455, 7.4866871584699455, 5],
 [456, 6.981936409550046, 7],
 [457, 7.356094202898551, 19],
 [458, 8.945476025818351, 8],
 [459, 7.870092592592592, 18],
 [460, 7.0466428230805915, 16],
 [461, 8.665594582185491, 7],
 [462, 7.940470615243342, 7],
 [463, 10.461923167848699, 14],
 [464, 9.442911522633745, 6],
 [465, 7.675700136612022, 5],
 [466, 6.858849862258953, 7],
 [467, 6.566270491803279, 5],
 [468, 9.279741379310344, 17],
 [469, 6.274268824609734, 7],
 [470, 6.288820330969267, 14],
 [471, 6.573817632850242, 19],
 [472, 9.549096064814815, 9],
 [473, 10.073600381497377, 16],
 [474, 8.282119640387275, 8],
 [475, 7.572011452241716, 21],
 [476, 7.892468599033816, 19],
 [477, 7.299837962962963, 21],
 [478, 7.948020118884316, 6],
 [479, 6.514737854737854, 18],
 [480, 6.864897292250234, 11],
 [481, 7.0701593999062355, 12],
 [482, 7.269061499771376, 6],
 [483, 6.906763538748833, 11],
 [484, 7.995794346978558, 21],
 [485, 6.163242702448211, 13],
 [486, 10.065310657596372, 4],
 [487, 6.56238722697056, 15],
 [488, 8.58901247645951, 13],
 [489, 6.2469322075379345, 22],
 [490, 8.346078216374268, 21],
 [491, 7.628272532188841, 16],
 [492, 5.989390301318267, 13],
 [493, 10.852765255009107, 5],
 [494, 6.414320175438596, 21],
 [495, 7.797098893499308, 8],
 [496, 10.776738425925926, 9],
 [497, 7.59499411487759, 13],
 [498, 7.366846136259716, 6],
 [499, 7.167783613445378, 11],
 [500, 7.034441015089163, 6],
 [501, 8.071109958506224, 8],
 [502, 6.645126366120219, 5],
 [503, 7.746935261707989, 7],
 [504, 6.059591642924976, 15],
 [505, 8.17237493987494, 18],
 [506, 9.181054189435336, 5],
 [507, 7.736015840220386, 7],
 [508, 7.559308461180846, 10],
 [509, 9.554978632478631, 15],
 [510, 7.231592995169082, 19],
 [511, 6.090823500491642, 23],
 [512, 7.678870748299319, 4],
 [513, 7.367792022792022, 15],
 [514, 7.541327941865917, 12],
 [515, 6.884659036719123, 16],
 [516, 6.579276819923372, 17],
 [517, 6.082369065100342, 22],
 [518, 7.891810742277547, 8],
 [519, 9.077365112025605, 6],
 [520, 6.592423580786026, 20],
 [521, 10.94496978149698, 10],
 [522, 8.680530303030304, 7],
 [523, 7.388847340930674, 15],
 [524, 7.48564535440613, 17],
 [525, 6.227168495656151, 6],
 [526, 7.845290670417253, 12],
 [527, 7.263236714975846, 19],
 [528, 7.8918405695611575, 11],
 [529, 7.974954275262917, 6],
 [530, 6.7043121693121694, 18],
 [531, 6.584470736168267, 6],
 [532, 6.165156754264638, 8],
 [533, 6.384622079160706, 16],
 [534, 9.772660256410255, 15],
 [535, 7.761643619602134, 20],
 [536, 6.636463414634146, 3],
 [537, 6.657914292497626, 15],
 [538, 10.536580498866213, 4],
 [539, 10.855418981481481, 9],
 [540, 7.777210300429184, 16],
 [541, 10.169497863247862, 15],
 [542, 6.75210951730419, 5],
 [543, 6.2718510638297875, 14],
 [544, 10.419206187895213, 3],
 [545, 8.008897996357012, 5],
 [546, 7.090368753032508, 20],
 [547, 6.18428118908382, 21],
 [548, 5.990846503831418, 17],
 [549, 7.95074494949495, 7],
 [550, 10.655739991003149, 2],
 [551, 6.297311594202898, 19],
 [552, 6.866976090014065, 12],
 [553, 6.373172268907563, 11],
 [554, 7.3583141762452104, 17],
 [555, 7.092662795992714, 5],
 [556, 7.16850619933238, 16],
 [557, 5.957570873342478, 6],
 [558, 10.475467278719398, 13],
 [559, 6.166456843109204, 16],
 [560, 7.163935990338165, 19],
 [561, 6.5771308479532165, 21],
 [562, 7.4505299707602335, 21],
 [563, 6.5672671033478895, 20],
 [564, 7.144859903381643, 19],
 [565, 7.990564009661836, 19],
 [566, 7.073227969348658, 17],
 [567, 7.1742389340560075, 3],
 [568, 10.854775510204082, 4],
 [569, 6.493683628318584, 23],
 [570, 10.640421374764596, 13],
 [571, 6.9643073286052015, 14],
 [572, 8.946277777777777, 14],
 [573, 8.088138422035481, 11],
 [574, 7.0996717171717165, 18],
 [575, 7.968624772313297, 5],
 [576, 7.385077491654744, 16],
 [577, 7.056550724637681, 19],
 [578, 6.7749999999999995, 7],
 [579, 6.766852626685263, 10],
 [580, 6.686374643874644, 15],
 [581, 7.986928811928812, 18],
 [582, 7.661829004329004, 18],
 [583, 7.035718306412139, 22],
 [584, 7.873881578947368, 21],
 [585, 10.247588702147524, 11],
 [586, 7.491594650205761, 6],
 [587, 7.658059013370217, 8],
 [588, 10.475282388197325, 8],
 [589, 6.869395218002813, 12],
 [590, 7.463380201188842, 6],
 [591, 7.95325462962963, 9],
 [592, 7.479908550525835, 6],
 [593, 6.566509502923977, 21],
 [594, 6.255832104228122, 23],
 [595, 7.438050887021475, 11],
 [596, 7.254420037192004, 10],
 [597, 8.763109061930782, 5],
 [598, 6.746857567443987, 6],
 [599, 6.672640075973409, 15],
 [600, 10.358641173641173, 18],
 [601, 5.972394833104709, 6],
 [602, 8.856918659165494, 12],
 [603, 9.837617205813407, 12],
 [604, 5.968773540489642, 13],
 [605, 6.1457004310344825, 17],
 [606, 7.786923347398031, 12],
 [607, 7.154119212962963, 9],
 [608, 7.462115384615385, 15],
 [609, 6.764325221238938, 23],
 [610, 7.2000860065086005, 10],
 [611, 7.165739921337267, 23],
 [612, 7.260518049695265, 12],
 [613, 8.465672080979285, 13],
 [614, 6.53235315712188, 22],
 [615, 5.992415191740413, 23],
 [616, 6.5557108199902965, 20],
 [617, 5.9836340679522495, 7],
 [618, 7.559376465072668, 12],
 [619, 6.255813492063492, 11],
 [620, 6.190025362318841, 19],
 [621, 7.469703703703703, 9],
 [622, 8.582052533705253, 10],
 [623, 7.235793144208038, 14],
 [624, 8.357217473884141, 15],
 [625, 8.003630952380952, 11],
 [626, 6.030533000949668, 15],
 [627, 7.257867149758454, 19],
 [628, 7.982340136054422, 4],
 [629, 9.147914332399626, 11],
 [630, 9.490839002267574, 4],
 [631, 9.765182149362477, 5],
 [632, 9.139694802098235, 16],
 [633, 6.293377498837749, 10],
 [634, 5.980848765432099, 15],
 [635, 8.352560028248588, 13],
 [636, 7.345115942028986, 19],
 [637, 7.641984289617486, 5],
 [638, 8.557337962962963, 9],
 [639, 7.241500706214689, 13],
 [640, 7.341077546296296, 9],
 [641, 6.568230625583566, 11],
 [642, 6.67300339640951, 20],
 [643, 6.0623719707361685, 6],
 [644, 6.061382001836547, 7],
 [645, 7.951031746031746, 18],
 [646, 8.760514739229025, 4],
 [647, 6.154985016136468, 8],
 [648, 6.889428104575164, 11],
 [649, 5.96328314659197, 11],
 [650, 6.993726258309591, 15],
 [651, 10.987004985754986, 15],
 [652, 10.738438245112064, 16],
 [653, 7.453135964912281, 21],

In [46]:
with open('time_per_day_and_leaves.csv', 'w') as out_file:
    writer = csv.writer(out_file)
    writer.writerows([["EmployeeID", "Avg_Hours", "No_of_leaves"]])
    for row in range(4410):
        writer.writerows([time_worked_year_leave[row]])