# Extracting features from in_time.csv and out_time.csv

In [1]:
import pandas as pd
import numpy as np
import math
import csv

### Loading the CSV files

In [2]:
in_time = pd.read_csv("hr-analytics-case-study/in_time.csv")
out_time = pd.read_csv("hr-analytics-case-study/out_time.csv")

### Renaming the unnamed column to "EmployeeID"

In [3]:
in_time.rename(columns = {"Unnamed: 0": "EmployeeID"}, inplace = True) 
out_time.rename(columns = {"Unnamed: 0": "EmployeeID"}, inplace = True)

In [4]:
in_time.head()

,EmployeeID,2015-01-01,2015-01-02,2015-01-05,2015-01-06,2015-01-07,2015-01-08,2015-01-09,2015-01-12,2015-01-13,...,2015-12-18,2015-12-21,2015-12-22,2015-12-23,2015-12-24,2015-12-25,2015-12-28,2015-12-29,2015-12-30,2015-12-31
0,1,NaN,2015-01-02 09:43:45,2015-01-05 10:08:48,2015-01-06 09:54:26,2015-01-07 09:34:31,2015-01-08 09:51:09,2015-01-09 10:09:25,2015-01-12 09:42:53,2015-01-13 10:13:06,...,NaN,2015-12-21 09:55:29,2015-12-22 10:04:06,2015-12-23 10:14:27,2015-12-24 10:11:35,NaN,2015-12-28 10:13:41,2015-12-29 10:03:36,2015-12-30 09:54:12,2015-12-31 10:12:44
1,2,NaN,2015-01-02 10:15:44,2015-01-05 10:21:05,NaN,2015-01-07 09:45:17,2015-01-08 10:09:04,2015-01-09 09:43:26,2015-01-12 10:00:07,2015-01-13 10:43:29,...,2015-12-18 10:37:17,2015-12-21 09:49:02,2015-12-22 10:33:51,2015-12-23 10:12:10,NaN,NaN,2015-12-28 09:31:45,2015-12-29 09:55:49,2015-12-30 10:32:25,2015-12-31 09:27:20
2,3,NaN,2015-01-02 10:17:41,2015-01-05 09:50:50,2015-01-06 10:14:13,2015-01-07 09:47:27,2015-01-08 10:03:40,2015-01-09 10:05:49,2015-01-12 10:03:47,2015-01-13 10:21:26,...,2015-12-18 10:15:14,2015-12-21 10:10:28,2015-12-22 09:44:44,2015-12-23 10:15:54,2015-12-24 10:07:26,NaN,2015-12-28 09:42:05,2015-12-29 09:43:36,2015-12-30 09:34:05,2015-12-31 10:28:39
3,4,NaN,2015-01-02 10:05:06,2015-01-05 09:56:32,2015-01-06 10:11:07,2015-01-07 09:37:30,2015-01-08 10:02:08,2015-01-09 10:08:12,2015-01-12 10:13:42,2015-01-13 09:53:22,...,2015-12-18 10:17:38,2015-12-21 09:58:21,2015-12-22 10:04:25,2015-12-23 10:11:46,2015-12-24 09:43:15,NaN,2015-12-28 09:52:44,2015-12-29 09:33:16,2015-12-30 10:18:12,2015-12-31 10:01:15
4,5,NaN,2015-01-02 10:28:17,2015-01-05 09:49:58,2015-01-06 09:45:28,2015-01-07 09:49:37,2015-01-08 10:19:44,2015-01-09 10:00:50,2015-01-12 10:29:27,2015-01-13 09:59:32,...,2015-12-18 09:58:35,2015-12-21 10:03:41,2015-12-22 10:10:30,2015-12-23 10:13:36,2015-12-24 09:44:24,NaN,2015-12-28 10:05:15,2015-12-29 10:30:53,2015-12-30 09:18:21,2015-12-31 09:41:09

In [5]:
out_time.head()

,EmployeeID,2015-01-01,2015-01-02,2015-01-05,2015-01-06,2015-01-07,2015-01-08,2015-01-09,2015-01-12,2015-01-13,...,2015-12-18,2015-12-21,2015-12-22,2015-12-23,2015-12-24,2015-12-25,2015-12-28,2015-12-29,2015-12-30,2015-12-31
0,1,NaN,2015-01-02 16:56:15,2015-01-05 17:20:11,2015-01-06 17:19:05,2015-01-07 16:34:55,2015-01-08 17:08:32,2015-01-09 17:38:29,2015-01-12 16:58:39,2015-01-13 18:02:58,...,NaN,2015-12-21 17:15:50,2015-12-22 17:27:51,2015-12-23 16:44:44,2015-12-24 17:47:22,NaN,2015-12-28 18:00:07,2015-12-29 17:22:30,2015-12-30 17:40:56,2015-12-31 17:17:33
1,2,NaN,2015-01-02 18:22:17,2015-01-05 17:48:22,NaN,2015-01-07 17:09:06,2015-01-08 17:34:04,2015-01-09 16:52:29,2015-01-12 17:36:48,2015-01-13 18:00:13,...,2015-12-18 18:31:28,2015-12-21 17:34:16,2015-12-22 18:16:35,2015-12-23 17:38:18,NaN,NaN,2015-12-28 17:08:38,2015-12-29 17:54:46,2015-12-30 18:31:35,2015-12-31 17:40:58
2,3,NaN,2015-01-02 16:59:14,2015-01-05 17:06:46,2015-01-06 16:38:32,2015-01-07 16:33:21,2015-01-08 17:24:22,2015-01-09 16:57:30,2015-01-12 17:28:54,2015-01-13 17:21:25,...,2015-12-18 17:02:23,2015-12-21 17:20:17,2015-12-22 16:32:50,2015-12-23 16:59:43,2015-12-24 16:58:25,NaN,2015-12-28 16:43:31,2015-12-29 17:09:56,2015-12-30 17:06:25,2015-12-31 17:15:50
3,4,NaN,2015-01-02 17:25:24,2015-01-05 17:14:03,2015-01-06 17:07:42,2015-01-07 16:32:40,2015-01-08 16:53:11,2015-01-09 17:19:47,2015-01-12 17:13:37,2015-01-13 17:11:45,...,2015-12-18 17:55:23,2015-12-21 16:49:09,2015-12-22 17:24:00,2015-12-23 17:36:35,2015-12-24 16:48:21,NaN,2015-12-28 17:19:34,2015-12-29 16:58:16,2015-12-30 17:40:11,2015-12-31 17:09:14
4,5,NaN,2015-01-02 18:31:37,2015-01-05 17:49:15,2015-01-06 17:26:25,2015-01-07 17:37:59,2015-01-08 17:59:28,2015-01-09 17:44:08,2015-01-12 18:51:21,2015-01-13 18:14:58,...,2015-12-18 17:52:48,2015-12-21 17:43:35,2015-12-22 18:07:57,2015-12-23 18:00:49,2015-12-24 17:59:22,NaN,2015-12-28 17:44:59,2015-12-29 18:47:00,2015-12-30 17:15:33,2015-12-31 17:42:14

### Extracting the time from datetime value

In [6]:
for i in range(1,262):
    in_time.iloc[:,i] =  pd.to_datetime(in_time.iloc[:,i]).dt.time
    out_time.iloc[:,i] = pd.to_datetime(out_time.iloc[:,i]).dt.time

In [7]:
in_time.head()

,EmployeeID,2015-01-01,2015-01-02,2015-01-05,2015-01-06,2015-01-07,2015-01-08,2015-01-09,2015-01-12,2015-01-13,...,2015-12-18,2015-12-21,2015-12-22,2015-12-23,2015-12-24,2015-12-25,2015-12-28,2015-12-29,2015-12-30,2015-12-31
0,1,NaT,09:43:45,10:08:48,09:54:26,09:34:31,09:51:09,10:09:25,09:42:53,10:13:06,...,NaT,09:55:29,10:04:06,10:14:27,10:11:35,NaT,10:13:41,10:03:36,09:54:12,10:12:44
1,2,NaT,10:15:44,10:21:05,NaT,09:45:17,10:09:04,09:43:26,10:00:07,10:43:29,...,10:37:17,09:49:02,10:33:51,10:12:10,NaT,NaT,09:31:45,09:55:49,10:32:25,09:27:20
2,3,NaT,10:17:41,09:50:50,10:14:13,09:47:27,10:03:40,10:05:49,10:03:47,10:21:26,...,10:15:14,10:10:28,09:44:44,10:15:54,10:07:26,NaT,09:42:05,09:43:36,09:34:05,10:28:39
3,4,NaT,10:05:06,09:56:32,10:11:07,09:37:30,10:02:08,10:08:12,10:13:42,09:53:22,...,10:17:38,09:58:21,10:04:25,10:11:46,09:43:15,NaT,09:52:44,09:33:16,10:18:12,10:01:15
4,5,NaT,10:28:17,09:49:58,09:45:28,09:49:37,10:19:44,10:00:50,10:29:27,09:59:32,...,09:58:35,10:03:41,10:10:30,10:13:36,09:44:24,NaT,10:05:15,10:30:53,09:18:21,09:41:09

In [8]:
out_time.head()

,EmployeeID,2015-01-01,2015-01-02,2015-01-05,2015-01-06,2015-01-07,2015-01-08,2015-01-09,2015-01-12,2015-01-13,...,2015-12-18,2015-12-21,2015-12-22,2015-12-23,2015-12-24,2015-12-25,2015-12-28,2015-12-29,2015-12-30,2015-12-31
0,1,NaT,16:56:15,17:20:11,17:19:05,16:34:55,17:08:32,17:38:29,16:58:39,18:02:58,...,NaT,17:15:50,17:27:51,16:44:44,17:47:22,NaT,18:00:07,17:22:30,17:40:56,17:17:33
1,2,NaT,18:22:17,17:48:22,NaT,17:09:06,17:34:04,16:52:29,17:36:48,18:00:13,...,18:31:28,17:34:16,18:16:35,17:38:18,NaT,NaT,17:08:38,17:54:46,18:31:35,17:40:58
2,3,NaT,16:59:14,17:06:46,16:38:32,16:33:21,17:24:22,16:57:30,17:28:54,17:21:25,...,17:02:23,17:20:17,16:32:50,16:59:43,16:58:25,NaT,16:43:31,17:09:56,17:06:25,17:15:50
3,4,NaT,17:25:24,17:14:03,17:07:42,16:32:40,16:53:11,17:19:47,17:13:37,17:11:45,...,17:55:23,16:49:09,17:24:00,17:36:35,16:48:21,NaT,17:19:34,16:58:16,17:40:11,17:09:14
4,5,NaT,18:31:37,17:49:15,17:26:25,17:37:59,17:59:28,17:44:08,18:51:21,18:14:58,...,17:52:48,17:43:35,18:07:57,18:00:49,17:59:22,NaT,17:44:59,18:47:00,17:15:33,17:42:14

### Dropping the columns that contain NULL values for all the rows as these are Company Holidays.

In [9]:
in_time = in_time.dropna(axis=1, how="all")
out_time = out_time.dropna(axis=1, how="all")

### The in_time and corresponding out_time have NULL values indicating that the employee was on leave on that specific day.

In [10]:
print(in_time.isna().sum()) #250
print(out_time.isna().sum()) #250

EmployeeID      0
2015-01-02    209
2015-01-05    206
2015-01-06    228
2015-01-07    209
             ...
2015-12-24    250
2015-12-28    234
2015-12-29    230
2015-12-30    265
2015-12-31    213
Length: 250, dtype: int64
EmployeeID      0
2015-01-02    209
2015-01-05    206
2015-01-06    228
2015-01-07    209
             ...
2015-12-24    250
2015-12-28    234
2015-12-29    230
2015-12-30    265
2015-12-31    213
Length: 250, dtype: int64

### 'in_time' data and 'out_time' data stored as numpy arrays for faster computation.

In [11]:
emp_in = in_time.iloc[:,1:]
emp_in = np.array(emp_in)
emp_out = out_time.iloc[:,1:]
emp_out = np.array(emp_out)

In [12]:
emp_out.shape

(4410, 249)

### Calculating the total working time of an employee per day (in seconds)

In [13]:
sub_time = []
for i in range(4410):
    t = []
    t.append(i+1)
    for j in range(249):
        diff_h = (emp_out[i][j].hour - emp_in[i][j].hour)*60*60
        diff_m = (emp_out[i][j].minute - emp_in[i][j].minute)
        diff_s = emp_out[i][j].second - emp_in[i][j].second
        time_worked = diff_h + diff_m + diff_s
        t.append(time_worked)
    sub_time.append(t)

In [14]:
in_time.columns

Index(['EmployeeID', '2015-01-02', '2015-01-05', '2015-01-06', '2015-01-07',
       '2015-01-08', '2015-01-09', '2015-01-12', '2015-01-13', '2015-01-15',
       ...
       '2015-12-17', '2015-12-18', '2015-12-21', '2015-12-22', '2015-12-23',
       '2015-12-24', '2015-12-28', '2015-12-29', '2015-12-30', '2015-12-31'],
      dtype='object', length=250)

### The calculated total work time is written to a CSV file.

In [15]:
with open('total_work_time.csv', 'w') as output_file:
    writer = csv.writer(output_file)
    writer.writerows([in_time.columns])
    for row in range(4410):
        writer.writerows([sub_time[row]])

### Calculating the average work time and the number of leaves taken.

In [16]:
time_worked_year_leave = []
for i in range(4410):
    count = 0
    sum_seconds = 0
    for j in range(249):
        if math.isnan(sub_time[i][j]):
            count = count + 1
        else:
            sum_seconds = sum_seconds + sub_time[i][j]
    time_worked_year_leave.append([i+1, ((sum_seconds/3600)/(249-count)), count])

In [17]:
time_worked_year_leave

[[1, 7.3782423371647505, 17],
 [2, 7.712582391713748, 13],
 [3, 6.954793388429752, 7],
 [4, 7.187041371158393, 14],
 [5, 8.011515873015872, 4],
 [6, 10.738615799343647, 12],
 [7, 6.952101293103448, 17],
 [8, 6.707770919067215, 6],
 [9, 7.225381642512077, 19],
 [10, 7.097961775878442, 15],
 [11, 8.348801290917473, 8],
 [12, 7.045671968649146, 8],
 [13, 9.21883066472586, 20],
 [14, 9.395913711583924, 14],
 [15, 6.087533425541724, 8],
 [16, 6.613014533520863, 12],
 [17, 6.585233724914342, 22],
 [18, 10.942976513098465, 3],
 [19, 6.901147030651341, 17],
 [20, 9.265248917748918, 18],
 [21, 7.539130747126437, 17],
 [22, 6.004393399810066, 15],
 [23, 8.378706896551723, 17],
 [24, 6.822402433425161, 7],
 [25, 7.082138047138048, 18],
 [26, 9.320372291378517, 8],
 [27, 10.942247791724778, 10],
 [28, 7.525562617702448, 13],
 [29, 10.942409693644262, 6],
 [30, 6.799002415458937, 19],
 [31, 10.06734010270775, 11],
 [32, 6.660880394857667, 7],
 [33, 10.453716761633428, 15],
 [34, 6.160427526291724, 6],
 [35, 6.56640625, 9],
 [36, 10.288413553639847, 17],
 [37, 9.918557162534436, 7],
 [38, 5.994806397306398, 18],
 [39, 6.736078071463534, 22],
 [40, 7.66950720595072, 10],
 [41, 7.1633014571949, 5],
 [42, 7.520209219858156, 14],
 [43, 6.885067722681359, 7],
 [44, 6.99641087962963, 9],
 [45, 7.216613160291439, 5],
 [46, 7.145079861111111, 9],
 [47, 7.584732860520095, 14],
 [48, 7.805732536333802, 12],
 [49, 6.9166483113069015, 22],
 [50, 6.8380482456140355, 21],
 [51, 10.863679981634528, 7],
 [52, 9.152120253164556, 12],
 [53, 6.778963272896327, 10],
 [54, 7.28412429378531, 13],
 [55, 8.582576275045538, 5],
 [56, 6.752408963585434, 11],
 [57, 10.971407029478458, 4],
 [58, 7.638788546255507, 22],
 [59, 9.905408093278464, 6],
 [60, 7.894363086936308, 10],
 [61, 10.599729052823315, 5],
 [62, 10.464868665736867, 10],
 [63, 10.0128367003367, 18],
 [64, 6.580392089620485, 6],
 [65, 7.480352789498359, 12],
 [66, 10.660170940170941, 2],
 [67, 6.1340589080459775, 17],
 [68, 6.546921194322075, 22],
 [69, 6.073887670565302, 21],
 [70, 9.942148825654924, 3],
 [71, 7.384075987144168, 7],
 [72, 6.453103566529493, 6],
 [73, 6.289152482269503, 14],
 [74, 9.256174843674845, 18],
 [75, 6.0225441106342394, 16],
 [76, 7.177056489262372, 11],
 [77, 7.0825906795224975, 7],
 [78, 9.818376623376624, 18],
 [79, 10.430599033816424, 19],
 [80, 6.804708275220827, 10],
 [81, 7.581011733716474, 17],
 [82, 6.053864981785064, 5],
 [83, 6.0245409604519775, 13],
 [84, 8.909747474747475, 7],
 [85, 10.332822128851541, 11],
 [86, 8.39304189435337, 5],
 [87, 7.888257033857893, 16],
 [88, 7.079627285513362, 12],
 [89, 9.607683635518365, 10],
 [90, 7.769392143189215, 10],
 [91, 6.261744022503516, 12],
 [92, 6.232877920839294, 16],
 [93, 8.76799829434698, 21],
 [94, 7.705875239463602, 17],
 [95, 7.266697663328564, 16],
 [96, 10.765714125056231, 2],
 [97, 10.404020408163266, 4],
 [98, 6.0073994055784175, 6],
 [99, 6.120405625290563, 10],
 [100, 8.126176001821493, 5],
 [101, 7.26370929118774, 17],
 [102, 7.063012371615312, 11],
 [103, 6.285669030732861, 14],
 [104, 8.074073676680973, 16],
 [105, 7.9476382823871905, 20],
 [106, 10.450502645502645, 18],
 [107, 8.016467051467052, 18],
 [108, 6.078254142300195, 21],
 [109, 7.545882212684788, 16],
 [110, 6.865403381642512, 19],
 [111, 9.269056267806267, 15],
 [112, 10.731808943089431, 3],
 [113, 5.96644806763285, 19],
 [114, 7.779246031746032, 4],
 [115, 7.686011064030132, 13],
 [116, 6.14490780141844, 14],
 [117, 7.111187739463602, 17],
 [118, 7.779973379629629, 9],
 [119, 7.583827972709552, 21],
 [120, 5.991029202279202, 15],
 [121, 9.09291962174941, 14],
 [122, 8.61930202448211, 13],
 [123, 9.9864384057971, 19],
 [124, 6.8952405002405, 18],
 [125, 6.958255787037037, 9],
 [126, 6.272508417508417, 18],
 [127, 6.359467984934087, 13],
 [128, 8.2075, 9],
 [129, 6.45817824074074, 9],
 [130, 6.618227053140097, 19],
 [131, 7.433839243498817, 14],
 [132, 9.877951247165534, 4],
 [133, 7.430761534839925, 13],
 [134, 7.475323295985061, 11],
 [135, 5.974214390602056, 22],
 [136, 6.799212962962963, 15],
 [137, 6.116290708812261, 17],
 [138, 7.599263338228096, 22],
 [139, 8.865289449112979, 11],
 [140, 10.815427442528737, 17],
 [141, 10.619103481163567, 16],
 [142, 6.98270474137931, 17],
 [143, 8.983801587301588, 4],
 [144, 7.323307763830776, 10],
 [145, 7.58712358276644, 4],
 [146, 6.552947210696173, 8],
 [147, 6.186024011299435, 13],
 [148, 6.428639359698682, 13],
 [149, 8.184961133973479, 6],
 [150, 6.726034927332396, 12],
 [151, 7.322873522458629, 14],
 [152, 6.815796375774917, 16],
 [153, 7.265555555555555, 19],
 [154, 6.155116139846743, 17],
 [155, 7.5362458977965305, 12],
 [156, 6.5384302054155, 11],
 [157, 10.572711864406779, 13],
 [158, 6.1417670093000485, 22],
 [159, 8.524576887013595, 12],
 [160, 5.978688071188071, 18],
 [161, 6.269103034752814, 22],
 [162, 7.834516856600191, 15],
 [163, 7.144931129476584, 7],
 [164, 6.603913502109705, 12],
 [165, 7.817505935422602, 15],
 [166, 6.698542538354253, 10],
 [167, 6.272794612794613, 18],
 [168, 7.208972336534066, 6],
 [169, 6.287153935185185, 9],
 [170, 7.262585377585377, 18],
 [171, 7.7664879227053145, 19],
 [172, 6.801721763085399, 7],
 [173, 6.445122269705603, 15],
 [174, 7.663786307053942, 8],
 [175, 7.534478869895536, 15],
 [176, 9.157827635327637, 15],
 [177, 6.381046374764595, 13],
 [178, 8.448926875593543, 15],
 [179, 6.946944444444444, 5],
 [180, 6.456509912402028, 8],
 [181, 8.82682277318641, 7],
 [182, 6.514239766081872, 21],
 [183, 10.875079699953117, 12],
 [184, 7.7420868644067795, 13],
 [185, 7.24102800546448, 5],
 [186, 6.335201804368471, 15],
 [187, 6.728032708032708, 18],
 [188, 7.362440898345153, 14],
 [189, 6.161294685990338, 19],
 [190, 5.9492978063900805, 16],
 [191, 7.315545309653917, 5],
 [192, 7.090346648301193, 7],
 [193, 8.66553145087236, 7],
 [194, 10.783578154425612, 13],
 [195, 7.38541912487709, 23],
 [196, 9.151367258652094, 5],
 [197, 7.337937378167641, 21],
 [198, 7.378059013370217, 8],
 [199, 6.683645536562203, 15],
 [200, 9.187641770401108, 8],
 [201, 6.865818224081822, 10],
 [202, 9.22224154589372, 19],
 [203, 6.003930131004367, 20],
 [204, 6.251694688109161, 21],
 [205, 6.347300750117206, 12],
 [206, 8.68355746304244, 16],
 [207, 7.38315625, 9],
 [208, 6.1839973196881095, 21],
 [209, 7.673750581125058, 10],
 [210, 7.4968660673121255, 8],
 [211, 9.069735883424409, 5],
 [212, 6.01187989857077, 8],
 [213, 5.984147153351699, 7],
 [214, 5.971442352394235, 10],
 [215, 6.882373417721519, 12],
 [216, 10.698471645919778, 8],
 [217, 8.927210197210199, 18],
 [218, 7.309383859167809, 6],
 [219, 6.818352490421455, 17],
 [220, 6.738319672131148, 5],
 [221, 7.370871267743514, 22],
 [222, 10.781403568202348, 3],
 [223, 6.888334525512637, 16],
 [224, 8.87455747955748, 18],
 [225, 6.628652952115295, 10],
 [226, 7.916118084611808, 10],
 [227, 6.29849477682811, 15],
 [228, 7.830118549511855, 10],
 [229, 8.814577046181986, 6],
 [230, 7.062827134986226, 7],
 [231, 7.434717494089835, 14],
 [232, 8.62511224489796, 4],
 [233, 6.735989439853077, 7],
 [234, 9.071335162322818, 6],
 [235, 6.979268635724331, 12],
 [236, 6.69728313840156, 21],
 [237, 8.373989031950405, 16],
 [238, 6.5019874476987445, 10],
 [239, 7.239380434782608, 19],
 [240, 8.684961685823755, 17],
 [241, 5.987887909936369, 22],
 [242, 7.222105200945626, 14],
 [243, 9.330369605142332, 7],
 [244, 7.316009142053446, 12],
 [245, 7.098368794326241, 14],
 [246, 7.372688284518828, 10],
 [247, 7.5571539961013645, 21],
 [248, 9.893986794171221, 5],
 [249, 6.18125116713352, 11],
 [250, 6.761806742640076, 15],
 [251, 6.620806375996249, 12],
 [252, 7.446580578512397, 7],
 [253, 6.360031676413255, 21],
 [254, 10.6712517580872, 12],
 [255, 6.999648550724637, 19],
 [256, 8.648277545327755, 10],
 [257, 10.346011743450767, 3],
 [258, 6.658781866281867, 18],
 [259, 7.051597815764483, 15],
 [260, 7.631097279852466, 8],
 [261, 6.76931129476584, 7],
 [262, 7.760532508491024, 20],
 [263, 7.065214975845411, 19],
 [264, 8.8134650997151, 15],
 [265, 7.5812166424065985, 20],
 [266, 9.093820009033424, 3],
 [267, 6.758247126436782, 17],
 [268, 7.5022694790225914, 8],
 [269, 6.640799952312828, 16],
 [270, 7.859007597340931, 15],
 [271, 8.238547877145438, 3],
 [272, 7.103505007153076, 16],
 [273, 6.463476430976431, 18],
 [274, 7.933973429951691, 19],
 [275, 6.655549568965518, 17],
 [276, 8.566845730027548, 7],
 [277, 6.70937922705314, 19],
 [278, 7.6781522271169855, 22],
 [279, 6.50351031411158, 12],
 [280, 7.350342240975152, 12],
 [281, 6.177011206485455, 16],
 [282, 7.3400930004894755, 22],
 [283, 8.01800339640951, 20],
 [284, 5.921663165266106, 11],
 [285, 9.802789907811743, 20],
 [286, 6.078559243891195, 8],
 [287, 8.277477053140096, 19],
 [288, 7.465033381020506, 16],
 [289, 6.383174439871971, 6],
 [290, 10.020302083333332, 9],
 [291, 7.047310499058381, 13],
 [292, 6.362592592592592, 6],
 [293, 7.770804473304473, 18],
 [294, 6.327913785154449, 8],
 [295, 7.183202193609919, 16],
 [296, 8.777820512820513, 15],
 [297, 7.4432308743169395, 5],
 [298, 7.091373119844735, 20],
 [299, 6.273312530592266, 22],
 [300, 7.103291245791246, 18],
 [301, 7.754816446402349, 22],
 [302, 10.849013127051103, 12],
 [303, 6.177133520074697, 11],
 [304, 5.982588985088985, 18],
 [305, 10.008146591970121, 11],
 [306, 7.621570881226053, 17],
 [307, 5.878547281323877, 14],
 [308, 7.944616858237548, 17],
 [309, 9.965633381226054, 17],
 [310, 7.734222449908925, 5],
 [311, 7.9422756857275685, 10],
 [312, 7.396602011494253, 17],
 [313, 7.207193526170799, 7],
 [314, 7.069163074712644, 17],
 [315, 6.279512731481481, 9],
 [316, 6.183067632850242, 19],
 [317, 6.187899814039982, 10],
 [318, 8.853117030965391, 5],
 [319, 6.777571195144724, 11],
 [320, 9.416252857796067, 6],
 [321, 10.736052571166208, 7],
 [322, 6.892845117845118, 18],
 [323, 7.74622495446266, 5],
 [324, 7.144751461988304, 21],
 [325, 6.472902377686329, 6],
 [326, 7.921203299369238, 20],
 [327, 7.769647612488521, 7],
 [328, 7.929075246132208, 12],
 [329, 6.825651221761181, 8],
 [330, 6.033982653539615, 12],
 [331, 6.356840866290019, 13],
 [332, 10.602029569892473, 1],
 [333, 6.983900414937759, 8],
 [334, 8.011689623507806, 7],
 [335, 9.411802054154997, 11],
 [336, 7.636845760233918, 21],
 [337, 7.666485455412494, 16],
 [338, 8.820490900383142, 17],
 [339, 7.722332395686826, 12],
 [340, 10.38955459770115, 17],
 [341, 6.174314009661836, 19],
 [342, 6.571458333333333, 21],
 [343, 7.894388170498084, 17],
 [344, 6.86302801724138, 17],
 [345, 9.33474149659864, 4],
 [346, 6.6311002886002886, 18],
 [347, 7.5715706447187925, 6],
 [348, 7.570618686868687, 7],
 [349, 6.8306099290780145, 14],
 [350, 6.27299062049062, 18],
 [351, 6.334714912280702, 21],
 [352, 7.316963684463684, 18],
 [353, 10.45312559354226, 15],
 [354, 6.962098506069094, 11],
 [355, 9.901756602914391, 5],
 [356, 6.86063246097337, 7],
 [357, 7.9700374396135265, 19],
 [358, 7.310071428571429, 4],
 [359, 6.065347522847523, 18],
 [360, 6.2690655509065545, 10],
 [361, 6.393879551820729, 11],
 [362, 5.9472890733056705, 8],
 [363, 6.866671476671476, 18],
 [364, 9.693660756501183, 14],
 [365, 7.785689696106362, 15],
 [366, 6.409109903381642, 19],
 [367, 10.340086167800452, 4],
 [368, 8.481276371308017, 12],
 [369, 6.570989439853077, 7],
 [370, 7.547780151946819, 15],
 [371, 6.058826648224989, 8],
 [372, 6.308105726872247, 22],
 [373, 6.453722461685823, 17],
 [374, 10.929960973370065, 7],
 [375, 7.962056277056277, 18],
 [376, 7.586991505968778, 7],
 [377, 10.36647462277092, 6],
 [378, 8.760131004366812, 20],
 [379, 10.011705146705147, 18],
 [380, 7.852382338670548, 20],
 [381, 7.742962962962963, 12],
 [382, 7.439464038727524, 8],
 [383, 7.535014492753623, 19],
 [384, 6.804248226950354, 14],
 [385, 6.907804849340867, 13],
 [386, 9.573878428637842, 10],
 [387, 10.012976851851851, 9],
 [388, 9.315242194674013, 7],
 [389, 6.3813745827372435, 16],
 [390, 7.118413370998117, 13],
 [391, 7.337397163120568, 14],
 [392, 6.660184426229509, 5],
 [393, 7.535610161443494, 15],
 [394, 10.619178051001821, 5],
 [395, 8.333268870135958, 12],
 [396, 6.549233674463938, 21],
 [397, 6.801504535147392, 4],
 [398, 9.390464924670434, 13],
 [399, 9.996532838506523, 2],
 [400, 6.422116736990155, 12],
 [401, 9.720274291027428, 10],
 [402, 6.319058981889378, 22],
 [403, 10.455173041894353, 5],
 [404, 6.536152604887045, 8],
 [405, 7.089444444444445, 15],
 [406, 7.884857142857142, 4],
 [407, 10.310658014571949, 5],
 [408, 8.451694796061885, 12],
 [409, 9.735248962655602, 8],
 [410, 10.364633237133237, 18],
 [411, 7.647747175141243, 13],
 [412, 10.599168991166898, 10],
 [413, 7.5993619246861925, 10],
 [414, 7.731478093947606, 3],
 [415, 6.843064083820663, 21],
 [416, 10.5084302054155, 11],
 [417, 8.306143654114365, 10],
 [418, 6.078686556927298, 6],
 [419, 10.275352474323062, 11],
 [420, 6.9499439675727235, 16],
 [421, 6.658262436076243, 10],
 [422, 7.0461270491803285, 5],
 [423, 6.46945839144584, 10],
 [424, 7.042382741347905, 5],
 [425, 7.094653351698806, 7],
 [426, 8.867824272770624, 16],
 [427, 6.001544985250737, 23],
 [428, 7.5699919317657915, 8],
 [429, 10.611863376251788, 16],
 [430, 7.079743230625583, 11],
 [431, 10.58516366989396, 8],
 [432, 6.034878328741965, 7],
 [433, 8.28680254930255, 18],
 [434, 8.15475850340136, 4],
 [435, 7.8089787234042545, 14],
 [436, 9.81403539615565, 12],
 [437, 5.988129553734062, 5],
 [438, 6.239001468428781, 22],
 [439, 6.284694092827005, 12],
 [440, 7.556557496360989, 20],
 [441, 6.371946788560713, 12],
 [442, 6.950524042950514, 11],
 [443, 7.431349033816425, 19],
 [444, 6.484467401285584, 7],
 [445, 7.96620936438622, 20],
 [446, 8.019039301310043, 20],
 [447, 7.258357946554149, 12],
 [448, 6.470225845410629, 19],
 [449, 9.41427684013127, 12],
 [450, 10.05161111111111, 14],
 [451, 6.704379017447199, 7],
 [452, 8.152141690009337, 11],
 [453, 7.8664403735632185, 17],
 [454, 10.24892639474918, 12],
 [455, 7.432012750455373, 5],
 [456, 7.00794191919192, 7],
 [457, 7.35637922705314, 19],
 [458, 8.9587367450438, 8],
 [459, 7.891518759018759, 18],
 [460, 7.021953981878874, 16],
 [461, 8.64927341597796, 7],
 [462, 7.954760101010101, 7],
 [463, 10.51513475177305, 14],
 [464, 9.428411065386374, 6],
 [465, 7.644064207650273, 5],
 [466, 6.830880394857668, 7],
 [467, 6.534097222222222, 5],
 [468, 9.297543103448277, 17],
 [469, 6.276910009182736, 7],
 [470, 6.3111371158392435, 14],
 [471, 6.608661835748792, 19],
 [472, 9.571221064814814, 9],
 [473, 10.124455174058179, 16],
 [474, 8.298508529276164, 8],
 [475, 7.539952485380117, 21],
 [476, 7.883989130434783, 19],
 [477, 7.268857212475633, 21],
 [478, 7.979314128943758, 6],
 [479, 6.48564935064935, 18],
 [480, 6.857116013071895, 11],
 [481, 7.084612048757618, 12],
 [482, 7.287676040237769, 6],
 [483, 6.916335200746966, 11],
 [484, 7.9617227095516565, 21],
 [485, 6.120117702448211, 13],
 [486, 10.086783446712019, 4],
 [487, 6.493890075973409, 15],
 [488, 8.618595809792843, 13],
 [489, 6.2384128732256485, 22],
 [490, 8.398695175438597, 21],
 [491, 7.618495469718646, 16],
 [492, 5.942654190207156, 13],
 [493, 10.865056921675775, 5],
 [494, 6.353221247563353, 21],
 [495, 7.80049907791609, 8],
 [496, 10.735015046296297, 9],
 [497, 7.560480225988701, 13],
 [498, 7.394633058984911, 6],
 [499, 7.185205415499533, 11],
 [500, 7.0384876543209876, 6],
 [501, 8.127689027201475, 8],
 [502, 6.611676912568306, 5],
 [503, 7.7196430211202935, 7],
 [504, 6.077311253561254, 15],
 [505, 8.187061087061087, 18],
 [506, 9.18461407103825, 5],
 [507, 7.68393709825528, 7],
 [508, 7.552519758251976, 10],
 [509, 9.54818494776828, 15],
 [510, 7.183566425120772, 19],
 [511, 6.080235988200591, 23],
 [512, 7.675057823129252, 4],
 [513, 7.384461063627731, 15],
 [514, 7.491262306610407, 12],
 [515, 6.897742012398665, 16],
 [516, 6.561687021072797, 17],
 [517, 6.127709251101321, 22],
 [518, 7.860189027201476, 8],
 [519, 9.082693187014174, 6],
 [520, 6.6113888888888885, 20],
 [521, 10.851162250116225, 10],
 [522, 8.633395316804409, 7],
 [523, 7.414761396011396, 15],
 [524, 7.495888409961686, 17],
 [525, 6.2751886145404665, 6],
 [526, 7.861195499296764, 12],
 [527, 7.2743526570048305, 19],
 [528, 7.924480625583567, 11],
 [529, 7.955800182898948, 6],
 [530, 6.680899470899471, 18],
 [531, 6.5282898948331045, 6],
 [532, 6.190250115260489, 8],
 [533, 6.378713638531234, 16],
 [534, 9.749057454890789, 15],
 [535, 7.743393983503154, 20],
 [536, 6.6230058717253835, 3],
 [537, 6.642225783475783, 15],
 [538, 10.506812925170067, 4],
 [539, 10.831040509259259, 9],
 [540, 7.781571292322366, 16],
 [541, 10.171458926875593, 15],
 [542, 6.767087887067396, 5],
 [543, 6.297585106382979, 14],
 [544, 10.40295054200542, 3],
 [545, 7.992374772313297, 5],
 [546, 7.097453905870937, 20],
 [547, 6.228200536062379, 21],
 [548, 5.975093390804597, 17],
 [549, 7.947494260789716, 7],
 [550, 10.617056905083222, 2],
 [551, 6.258049516908212, 19],
 [552, 6.870226207219877, 12],
 [553, 6.370280112044818, 11],
 [554, 7.375409482758621, 17],
 [555, 7.106700819672131, 5],
 [556, 7.234554124940391, 16],
 [557, 5.963303612254229, 6],
 [558, 10.491578389830508, 13],
 [559, 6.201485455412494, 16],
 [560, 7.15303381642512, 19],
 [561, 6.562970272904483, 21],
 [562, 7.435650584795322, 21],
 [563, 6.567911208151383, 20],
 [564, 7.183195652173913, 19],
 [565, 7.987357487922705, 19],
 [566, 7.074075670498084, 17],
 [567, 7.183366079494129, 3],
 [568, 10.869893424036281, 4],
 [569, 6.526026302851523, 23],
 [570, 10.640560263653486, 13],
 [571, 6.949940898345154, 14],
 [572, 8.971244680851063, 14],
 [573, 8.142676237161531, 11],
 [574, 7.120530303030303, 18],
 [575, 7.963452868852459, 5],
 [576, 7.420528135431569, 16],
 [577, 7.070231884057971, 19],
 [578, 6.777912075298439, 7],
 [579, 6.728726173872618, 10],
 [580, 6.668234805318138, 15],
 [581, 7.996010101010101, 18],
 [582, 7.641750841750842, 18],
 [583, 7.027920949583945, 22],
 [584, 7.847860623781677, 21],
 [585, 10.248690476190477, 11],
 [586, 7.50636488340192, 6],
 [587, 7.669687644075611, 8],
 [588, 10.50248386353158, 8],
 [589, 6.828111814345991, 12],
 [590, 7.420957933241883, 6],
 [591, 7.950454861111111, 9],
 [592, 7.45374028349337, 6],
 [593, 6.592746101364523, 21],
 [594, 6.287449606686332, 23],
 [595, 7.4627719421101775, 11],
 [596, 7.239196885169688, 10],
 [597, 8.730734289617486, 5],
 [598, 6.738022405121171, 6],
 [599, 6.6509983380816715, 15],
 [600, 10.385530303030302, 18],
 [601, 5.951352309099223, 6],
 [602, 8.853046179090482, 12],
 [603, 9.806706516643224, 12],
 [604, 5.945162429378532, 13],
 [605, 6.181091954022988, 17],
 [606, 7.743288795124238, 12],
 [607, 7.134111111111111, 9],
 [608, 7.4623955365622034, 15],
 [609, 6.813564405113078, 23],
 [610, 7.247126917712691, 10],
 [611, 7.168132989183874, 23],
 [612, 7.245788795124239, 12],
 [613, 8.499838747645951, 13],
 [614, 6.542099853157121, 22],
 [615, 6.0354904129793505, 23],
 [616, 6.5557108199902965, 20],
 [617, 6.061176538108356, 7],
 [618, 7.553636896390061, 12],
 [619, 6.285423669467787, 11],
 [620, 6.235130434782608, 19],
 [621, 7.425931712962963, 9],
 [622, 8.549206183170618, 10],
 [623, 7.200713947990543, 14],
 [624, 8.363801044634378, 15],
 [625, 7.997226890756302, 11],
 [626, 6.072485754985754, 15],
 [627, 7.209698067632851, 19],
 [628, 7.99264172335601, 4],
 [629, 9.180829831932773, 11],
 [630, 9.470837868480725, 4],
 [631, 9.779220173041896, 5],
 [632, 9.168181926561754, 16],
 [633, 6.256416782891678, 10],
 [634, 5.962989078822413, 15],
 [635, 8.369226694915254, 13],
 [636, 7.369770531400966, 19],
 [637, 7.635737704918032, 5],
 [638, 8.542451388888889, 9],
 [639, 7.26275070621469, 13],
 [640, 7.280780092592592, 9],
 [641, 6.572224556489262, 11],
 [642, 6.67336123241145, 20],
 [643, 6.054481024234111, 6],
 [644, 6.082782369146005, 7],
 [645, 7.957417027417028, 18],
 [646, 8.776636054421768, 4],
 [647, 6.149884739511296, 8],
 [648, 6.887499999999999, 11],
 [649, 5.9636274509803915, 11],
 [650, 6.980138888888889, 15],
 [651, 10.949674738841404, 15],
 [652, 10.692085121602288, 16],
 [653, 7.452057748538012, 21],
 [654, 9.1603529143898, 5],
 [655, 8.625579365079366, 4],

### Extracted features written to a CSV file.

In [18]:
with open('extracted_features_from_in_out_time.csv', 'w') as out_file:
    writer = csv.writer(out_file)
    writer.writerows([["EmployeeID", "Avg_Hours", "No_of_leaves"]])
    for row in range(4410):
        writer.writerows([time_worked_year_leave[row]])